name: Static Analysis
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19.12"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
      - name: protoc
        uses: arduino/setup-protoc@v2
        with:
          version: '23.4'
      - run: make verify
